/*******************************************************************************
 * @title Simple Calculator
 * @author adityavkhandelwal@gmail.com
 * @date 16th May, 2019
 * 
 * A simple GUI based calculator using Java Swing API. Implemented using Apache 
 * Netbeans 11.0 Window Designer. Implements addition, subtraction, multiplication
 * and division in the same way as a pocket calculator. Supports decimals as well.
 *******************************************************************************/

/*******************************************************************************
 * ------------------------------- Calc2 class ---------------------------------
 * @author adityavkhandelwal@gmail.com
 * The Calc2 class contains the main method. It has an object of class Calculator
 * that implements the calculator functionality. This class only deals with the 
 * UI / UX part and provides a responsive interface to the user.
 * 
 * The display is implemented as a textBox object with editable = false. All the
 * buttons are implemented as Command Buttons and their events are handled by
 * this class. The operator display is implemented as four labels that are
 * disabled by default. Pressing the appropriate operator enables its label which
 * highlights it and disables all other operators.
 * 
 * See documentation of Calculator class for a description of its methods.
 *******************************************************************************/

public class Calc2 extends javax.swing.JFrame {
    //Create a final object of type Calculator to implement the functionality.
    //final because the memory address of the object calc is never changed
    private final Calculator calc = new Calculator();
    public Calc2() {
        initComponents(); //initializes the appearance of the GUI and declares the event handlers
        //toString method always returns the appropriate display
        display.setText(calc.toString()); 
    }

    //This method is called from within the constructor to initialize the form
    @SuppressWarnings("unchecked")
    //Below is the code auto-generated by the IDE to implement the GUI.
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmd1 = new javax.swing.JButton();
        cmd2 = new javax.swing.JButton();
        cmd3 = new javax.swing.JButton();
        cmd4 = new javax.swing.JButton();
        cmd5 = new javax.swing.JButton();
        cmd6 = new javax.swing.JButton();
        cmd7 = new javax.swing.JButton();
        cmd8 = new javax.swing.JButton();
        cmd9 = new javax.swing.JButton();
        cmd0 = new javax.swing.JButton();
        cmdDot = new javax.swing.JButton();
        cmdPlus = new javax.swing.JButton();
        cmdMinus = new javax.swing.JButton();
        cmdMultiply = new javax.swing.JButton();
        cmdDivide = new javax.swing.JButton();
        cmdEqual = new javax.swing.JButton();
        displayPane = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        cmdPM = new javax.swing.JButton();
        cmdAC = new javax.swing.JButton();
        cmdC = new javax.swing.JButton();
        labelPlus = new javax.swing.JLabel();
        labelMinus = new javax.swing.JLabel();
        labelMultiply = new javax.swing.JLabel();
        labelDivide = new javax.swing.JLabel();
        cmdAns = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Calculator");
        setResizable(false);

        jLabel1.setText("Calculator v1.0");

        cmd1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmd1.setText("1");
        cmd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd1ActionPerformed(evt);
            }
        });

        cmd2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmd2.setText("2");
        cmd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd2ActionPerformed(evt);
            }
        });

        cmd3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmd3.setText("3");
        cmd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd3ActionPerformed(evt);
            }
        });

        cmd4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmd4.setText("4");
        cmd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd4ActionPerformed(evt);
            }
        });

        cmd5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmd5.setText("5");
        cmd5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd5ActionPerformed(evt);
            }
        });

        cmd6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmd6.setText("6");
        cmd6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd6ActionPerformed(evt);
            }
        });

        cmd7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmd7.setText("7");
        cmd7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd7ActionPerformed(evt);
            }
        });

        cmd8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmd8.setText("8");
        cmd8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd8ActionPerformed(evt);
            }
        });

        cmd9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmd9.setText("9");
        cmd9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd9ActionPerformed(evt);
            }
        });

        cmd0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmd0.setText("0");
        cmd0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd0ActionPerformed(evt);
            }
        });

        cmdDot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdDot.setText(".");
        cmdDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDotActionPerformed(evt);
            }
        });

        cmdPlus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdPlus.setText("+");
        cmdPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPlusActionPerformed(evt);
            }
        });

        cmdMinus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdMinus.setText("-");
        cmdMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMinusActionPerformed(evt);
            }
        });

        cmdMultiply.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdMultiply.setText("X");
        cmdMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMultiplyActionPerformed(evt);
            }
        });

        cmdDivide.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdDivide.setText("/");
        cmdDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDivideActionPerformed(evt);
            }
        });

        cmdEqual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdEqual.setText("=");
        cmdEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEqualActionPerformed(evt);
            }
        });

        display.setEditable(false);
        display.setColumns(20);
        display.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        display.setLineWrap(true);
        display.setRows(5);
        displayPane.setViewportView(display);

        cmdPM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdPM.setText("±");
        cmdPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPMActionPerformed(evt);
            }
        });

        cmdAC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdAC.setText("AC");
        cmdAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdACActionPerformed(evt);
            }
        });

        cmdC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdC.setText("C");
        cmdC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCActionPerformed(evt);
            }
        });

        labelPlus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelPlus.setText("+");
        labelPlus.setEnabled(false);

        labelMinus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelMinus.setText("-");
        labelMinus.setEnabled(false);

        labelMultiply.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelMultiply.setText("X");
        labelMultiply.setEnabled(false);

        labelDivide.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelDivide.setText("/");
        labelDivide.setEnabled(false);

        cmdAns.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdAns.setText("Ans");
        cmdAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAnsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(displayPane, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cmdAC, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(cmdC, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmd7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmd8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(cmd4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmd5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmd1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmdEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmd0, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmd2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPlus)
                                .addGap(38, 38, 38)
                                .addComponent(labelMinus))
                            .addComponent(cmd3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmd6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmd9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdDot, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdAns, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(labelMultiply)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDivide)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmdPlus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmdMinus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmdMultiply, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmdDivide, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmdPM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDivide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdAC, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdPM, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdC, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdAns, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd0, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdDot, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Code to implement the functionality of the UI starts here:
    //The 0 button
    private void cmd0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd0ActionPerformed
        calc.parseDigit(0);
        display.setText(calc.toString());
    }//GEN-LAST:event_cmd0ActionPerformed

    //The 1 button
    private void cmd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd1ActionPerformed
        calc.parseDigit(1);
        display.setText(calc.toString());
    }//GEN-LAST:event_cmd1ActionPerformed

    //The 2 button
    private void cmd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd2ActionPerformed
        calc.parseDigit(2);
        display.setText(calc.toString());
    }//GEN-LAST:event_cmd2ActionPerformed

    //The 3 button
    private void cmd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd3ActionPerformed
        calc.parseDigit(3);
        display.setText(calc.toString());
    }//GEN-LAST:event_cmd3ActionPerformed

    //The 4 button
    private void cmd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd4ActionPerformed
        calc.parseDigit(4);
        display.setText(calc.toString());
    }//GEN-LAST:event_cmd4ActionPerformed

    //The 5 button
    private void cmd5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd5ActionPerformed
        calc.parseDigit(5);
        display.setText(calc.toString());
    }//GEN-LAST:event_cmd5ActionPerformed

    //The 6 button
    private void cmd6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd6ActionPerformed
        calc.parseDigit(6);
        display.setText(calc.toString());
    }//GEN-LAST:event_cmd6ActionPerformed

    //The 7 button
    private void cmd7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd7ActionPerformed
        calc.parseDigit(7);
        display.setText(calc.toString());
    }//GEN-LAST:event_cmd7ActionPerformed

    //The 8 button
    private void cmd8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd8ActionPerformed
        calc.parseDigit(8);
        display.setText(calc.toString());
    }//GEN-LAST:event_cmd8ActionPerformed

    //The 9 button
    private void cmd9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd9ActionPerformed
        calc.parseDigit(9);
        display.setText(calc.toString());
    }//GEN-LAST:event_cmd9ActionPerformed

    //The . button (decimal point)
    private void cmdDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDotActionPerformed
        calc.decimal();
        display.setText(calc.toString());
    }//GEN-LAST:event_cmdDotActionPerformed

    //The = button
    //Here we disable all the operator labels
    private void cmdEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEqualActionPerformed
        calc.parseOperator('=');
        display.setText(calc.toString());
        labelPlus.setEnabled(false);
        labelMinus.setEnabled(false);
        labelMultiply.setEnabled(false);
        labelDivide.setEnabled(false);
    }//GEN-LAST:event_cmdEqualActionPerformed

    //The + button: The + label is enabled, others disabled.
    private void cmdPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPlusActionPerformed
        calc.parseOperator('+');
        display.setText(calc.toString());
        labelPlus.setEnabled(true);
        labelMinus.setEnabled(false);
        labelMultiply.setEnabled(false);
        labelDivide.setEnabled(false);
    }//GEN-LAST:event_cmdPlusActionPerformed

    //The - button: The - label is enabled, others disabled.
    private void cmdMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMinusActionPerformed
        calc.parseOperator('-');
        display.setText(calc.toString());
        labelPlus.setEnabled(false);
        labelMinus.setEnabled(true);
        labelMultiply.setEnabled(false);
        labelDivide.setEnabled(false);
    }//GEN-LAST:event_cmdMinusActionPerformed

    //The X button: The X label is enabled, others disabled.
    private void cmdMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMultiplyActionPerformed
        calc.parseOperator('*');
        display.setText(calc.toString());
        labelPlus.setEnabled(false);
        labelMinus.setEnabled(false);
        labelMultiply.setEnabled(true);
        labelDivide.setEnabled(false);
    }//GEN-LAST:event_cmdMultiplyActionPerformed

    //The / button: The / label is enabled, others disabled.
    private void cmdDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDivideActionPerformed
        calc.parseOperator('/');
        display.setText(calc.toString());
        labelPlus.setEnabled(false);
        labelMinus.setEnabled(false);
        labelMultiply.setEnabled(false);
        labelDivide.setEnabled(true);
    }//GEN-LAST:event_cmdDivideActionPerformed

    //The +/- button: Changes sign of the number being entered
    private void cmdPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPMActionPerformed
        calc.plusMinus();
        display.setText(calc.toString());
    }//GEN-LAST:event_cmdPMActionPerformed

    //All clear
    private void cmdACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdACActionPerformed
        calc.clear();
        display.setText(calc.toString());
        labelPlus.setEnabled(false);
        labelMinus.setEnabled(false);
        labelMultiply.setEnabled(false);
        labelDivide.setEnabled(false);
    }//GEN-LAST:event_cmdACActionPerformed

    //Partial Clear (Clear): Clears the display without resetting the calculator completely
    //Helps if user entered an incorrect number in a long sequence of numbers
    private void cmdCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCActionPerformed
        calc.softClear();
        display.setText(calc.toString());
    }//GEN-LAST:event_cmdCActionPerformed

    //sets the last answer obtained as the operand
    private void cmdAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAnsActionPerformed
        calc.lastAnswer();
        display.setText(calc.toString());
    }//GEN-LAST:event_cmdAnsActionPerformed

    /**
     * main method.
     * No command line arguments acceptable
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd0;
    private javax.swing.JButton cmd1;
    private javax.swing.JButton cmd2;
    private javax.swing.JButton cmd3;
    private javax.swing.JButton cmd4;
    private javax.swing.JButton cmd5;
    private javax.swing.JButton cmd6;
    private javax.swing.JButton cmd7;
    private javax.swing.JButton cmd8;
    private javax.swing.JButton cmd9;
    private javax.swing.JButton cmdAC;
    private javax.swing.JButton cmdAns;
    private javax.swing.JButton cmdC;
    private javax.swing.JButton cmdDivide;
    private javax.swing.JButton cmdDot;
    private javax.swing.JButton cmdEqual;
    private javax.swing.JButton cmdMinus;
    private javax.swing.JButton cmdMultiply;
    private javax.swing.JButton cmdPM;
    private javax.swing.JButton cmdPlus;
    private javax.swing.JTextArea display;
    private javax.swing.JScrollPane displayPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDivide;
    private javax.swing.JLabel labelMinus;
    private javax.swing.JLabel labelMultiply;
    private javax.swing.JLabel labelPlus;
    // End of variables declaration//GEN-END:variables
}
